---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockercap
spec:
  replicas: 2
  selector:
    matchLabels:
      name: dockercap
  template:
    metadata:
      labels:
        name: dockercap
    spec:
      containers:
      - name: application
        image: geepee2017/dockercap:6
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3001

